# Linear algebra

In [5]:
import numpy as np

In [2]:
np.__version__

'1.14.3'

## Matrix and vector products

Q1. Predict the results of the following code.

In [18]:
x = [1,2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y))
print(np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [21]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [26]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [31]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [45]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)


array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [58]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q,r = np.linalg.qr(x)
print("q = {},\n\n r = {}".format(q,r))

q = [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]],

 r = [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [60]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
u,s,vh = np.linalg.svd(x)
print("u = {}\n s= {}\n vh = {}".format(u,s,vh))

u = [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
 s= [3.       2.236068 2.       0.      ]
 vh = [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [-0.8944272  0.         0.         0.         0.4472136]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [65]:
x = np.diag((1, 2, 3))
eigenvals, eigenvecs = np.linalg.eig(x)
print("eigenvals = {} \neigenvecs=\n{}".format(eigenvals,eigenvecs))


eigenvals = [1. 2. 3.] 
eigenvecs=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [66]:
print(np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [74]:
x = np.arange(1, 10).reshape((3, 3))
print(np.linalg.norm(x,ord='fro'))
print(np.linalg.cond(x,p='fro'))
# 16.8819430161
# 4.56177073661e+17

16.881943016134134
3.193239515623568e+17


Q11. Calculate the determinant of x.

In [75]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x) 

-2.0000000000000004

Q12. Calculate the rank of x.

In [78]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [83]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)


(-1.0, 0.6931471805599455)

Q14. Return the sum along the diagonal of x.

In [84]:
x = np.eye(4)
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [85]:
x = np.array([[1., 2.], [3., 4.]])

np.invert(x)

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''